### ISSUE TITLE
Add PreLoader Animation To our Website

### ISSUE THREAD

**Issue by marizvi** [iiitv/arcadia-official-web#18]
Hello Sir,
I have a great idea to make this website look more dynamic and impressive.
I would like to add preloader animation to this website.

Kindly assign me this issue under contribute-a-thon'21.

**Comment by prathmeshkhandelwal1** [comment]
@marizvi I dont think this will be needed here, as the web is in the progress stage, we have other issues to fix earlier. Site loading optimizing is not the case here.

**Comment by marizvi** [comment]
Ok no problem sir.
